name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    #Operating systems
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]

    steps:
    - uses: actions/checkout@v3
    
    #SSH key
    - uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_LENNY_COLLISION }}
            ${{ secrets.SSH_PRIVATE_KEY_LENNY_OPTIMIZATION }}
            ${{ secrets.SSH_PRIVATE_KEY_LENNY_TOOLS }}
            ${{ secrets.SSH_PRIVATE_KEY_LENNY_GUI_OPENGL }}

    #Install dependencies
    - name: Install Linux Libraries
      if: runner.os == 'Linux'
      run : |
        sudo apt-get install libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    #Cmake (in Release mode)
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_release -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build_release --config Release

    - name: Run Tests
      working-directory: ${{github.workspace}}/build_release
      run: ctest -C Release --output-on-failure
